[routers]
R1 ansible_host=192.168.100.11 ansible_connection=docker
R2 ansible_host=192.168.100.12 ansible_connection=docker
R3 ansible_host=192.168.100.13 ansible_connection=docker

[switches]
SW1 ansible_host=192.168.100.14 ansible_connection=docker
SW2 ansible_host=192.168.100.15 ansible_connection=docker

[firewalls]
FW1 ansible_host=192.168.100.16 ansible_connection=docker

[all:vars]
ansible_user=root
ansible_connection=docker
